"""
Premium service: key generation, redemption, expiry management.
"""
import logging
from datetime import datetime, timedelta, timezone
from typing import Optional, Tuple

from app.services.database import DatabaseService
from app.utils.security import generate_premium_key

logger = logging.getLogger(__name__)


class PremiumService:
    """Manages premium key lifecycle and user premium status."""

    def __init__(self, db: DatabaseService):
        self.db = db

    async def generate_key(
        self,
        duration_days: int,
        created_by: int,
    ) -> str:
        """Generate and store a new premium key."""
        key = generate_premium_key()
        await self.db.create_premium_key(key, duration_days, created_by)
        logger.info(f"Premium key generated by {created_by}: {key} ({duration_days}d)")
        return key

    async def redeem_key(
        self,
        key: str,
        user_id: int,
    ) -> Tuple[bool, str]:
        """
        Attempt to redeem a premium key.
        Returns (success, message).
        """
        duration_days = await self.db.redeem_premium_key(key, user_id)

        if duration_days is None:
            return False, "Invalid or already used key."

        # Calculate new expiry
        user = await self.db.get_user(user_id)
        now = datetime.now(timezone.utc)

        if user and user.premium_expiry:
            expiry = user.premium_expiry
            if expiry.tzinfo is None:
                expiry = expiry.replace(tzinfo=timezone.utc)
            # Extend existing premium
            if expiry > now:
                new_expiry = expiry + timedelta(days=duration_days)
            else:
                new_expiry = now + timedelta(days=duration_days)
        else:
            new_expiry = now + timedelta(days=duration_days)

        await self.db.set_premium(user_id, new_expiry)

        expiry_str = new_expiry.strftime("%Y-%m-%d")
        logger.info(f"Premium key redeemed by {user_id}: {key}, expires {expiry_str}")
        return True, f"Premium activated until {expiry_str} ({duration_days} days)"

    async def get_premium_expiry(self, user_id: int) -> Optional[datetime]:
        """Get premium expiry datetime for a user."""
        user = await self.db.get_user(user_id)
        if user is None:
            return None
        return user.premium_expiry

    async def revoke_premium(self, user_id: int) -> None:
        """Revoke premium from a user."""
        await self.db.set_premium(user_id, datetime.now(timezone.utc))
        logger.info(f"Premium revoked for user {user_id}")

    async def extend_premium(self, user_id: int, days: int) -> datetime:
        """Extend premium by N days. Returns new expiry."""
        now = datetime.now(timezone.utc)
        user = await self.db.get_user(user_id)

        if user and user.premium_expiry:
            expiry = user.premium_expiry
            if expiry.tzinfo is None:
                expiry = expiry.replace(tzinfo=timezone.utc)
            base = expiry if expiry > now else now
        else:
            base = now

        new_expiry = base + timedelta(days=days)
        await self.db.set_premium(user_id, new_expiry)
        return new_expiry
